// Code generated by hero.
// source: cronmail/template/mail.html
// DO NOT EDIT!
package template

import (
	"bytes"
	"cronmail/model"
	"strconv"

	"github.com/shiyanhui/hero"
)

func WeaList(word model.Word, tip string, weaList []model.Weather, sList []model.News, bList []model.News, buffer *bytes.Buffer) {
	buffer.WriteString(`<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>

    <body>
        `)
	buffer.WriteString(`
    <h2 style="margin: 0;padding-top: 20px;padding-bottom: 20px;background-color:#f3f5f0;text-align:center;color:#050602">ONE · 一个</h2>
    <div style="text-align:center;padding-bottom: 8px;background-color:#f3f5f0;">
         <img src="`)
	hero.EscapeHTML(word.ImgURL, buffer)
	buffer.WriteString(`" style="width:100%;margin-top:0px;"  alt="">
         <div style="margin:10px auto;width:85%;color:#5f5e5e;" >`)
	hero.EscapeHTML(word.Title, buffer)
	buffer.WriteString(`</div>
    </div>
    <h3 style="margin-top: 8px;margin-bottom: 20px;background-color:#75a4f2;text-align:center;color:white">`)
	hero.EscapeHTML(tip, buffer)
	buffer.WriteString(`</h3>
    <div style="width:100%; margin-top: 20px;color:#5f5e5e;text-align:center;">
        <span style="display:block;margin-top:15px;color:#676767;font-size:15px">近期天气预报</span>
    `)
	for _, threeDaysData := range weaList {
		buffer.WriteString(`
        <div style="display: flex;margin-top:5px;height: 30px;line-height: 30px;justify-content: space-around;align-items: center;">
            <span style="width:15%; text-align:center;">`)
		hero.EscapeHTML(threeDaysData.Day, buffer)
		buffer.WriteString(`</span>
            <div style="width:25%; text-align:center;">
                <img style="height:26px;vertical-align:middle;" src='`)
		hero.EscapeHTML(threeDaysData.ImgUrl, buffer)
		buffer.WriteString(`' alt="">
                <span style="display:inline-block">`)
		hero.EscapeHTML(threeDaysData.Text, buffer)
		buffer.WriteString(`</span>
            </div>
            <span style="width:25%; text-align:center;">`)
		hero.EscapeHTML(threeDaysData.Temperature, buffer)
		buffer.WriteString(`</span>
            
            `)
		if threeDaysData.PollutionLevel == "level_1" {
			buffer.WriteString(`
                <div style="width:35%; ">
                        <span style="display:inline-block;padding:0 8px;line-height:25px;color:#8fc31f; border-radius:15px; text-align:center;">`)
			hero.EscapeHTML(threeDaysData.Pollution, buffer)
			buffer.WriteString(`</span>
                </div>
            `)
		}
		if threeDaysData.PollutionLevel == "level_2" {
			buffer.WriteString(`
                <div style="width:35%; ">
                        <span style="display:inline-block;padding:0 8px;line-height:25px;color:#d7af0e; border-radius:15px; text-align:center;">`)
			hero.EscapeHTML(threeDaysData.Pollution, buffer)
			buffer.WriteString(`</span>
                </div>
            `)
		}
		if threeDaysData.PollutionLevel == "level_3" {
			buffer.WriteString(`
                <div style="width:35%; ">
                        <span style="display:inline-block;padding:0 8px;line-height:25px;color:#f39800; border-radius:15px; text-align:center;">`)
			hero.EscapeHTML(threeDaysData.Pollution, buffer)
			buffer.WriteString(`</span>
                </div>
            `)
		}
		if threeDaysData.PollutionLevel == "level_4" {
			buffer.WriteString(`
                <div style="width:35%; ">
                        <span style="display:inline-block;padding:0 8px;line-height:25px;color:#e2361a; border-radius:15px; text-align:center;">`)
			hero.EscapeHTML(threeDaysData.Pollution, buffer)
			buffer.WriteString(`</span>
                </div>
            `)
		}
		if threeDaysData.PollutionLevel == "level_5" {
			buffer.WriteString(`
                <div style="width:35%; ">
                        <span style="display:inline-block;padding:0 8px;line-height:25px;color:#5f52a0; border-radius:15px; text-align:center;">`)
			hero.EscapeHTML(threeDaysData.Pollution, buffer)
			buffer.WriteString(`</span>
                </div>
            `)
		}
		if threeDaysData.PollutionLevel == "level_6" {
			buffer.WriteString(`
                <div style="width:35%; ">
                        <span style="display:inline-block;padding:0 8px;line-height:25px;color:#631541; border-radius:15px; text-align:center;">`)
			hero.EscapeHTML(threeDaysData.Pollution, buffer)
			buffer.WriteString(`</span>
                </div>    
            `)
		}
		buffer.WriteString(`
            
        </div>
    `)
	}
	buffer.WriteString(`
    <h3 style="margin-top: 20px;margin-bottom: 20px;background-color:#f85d00;color:white">Sina热搜</h3>
    `)
	for index, news := range sList {
		indexs := "Top"
		if index > 0 {
			indexs = strconv.Itoa(index)
		}
		buffer.WriteString(`
        <div style="display: flex;margin-top:5px;height: 30px;line-height: 30px;justify-content: space-around;align-items: center;">
            <p style="width:20%; color: #f26d5f;">`)
		hero.EscapeHTML(indexs, buffer)
		buffer.WriteString(`</p>
            <a style="width:80%; text-decoration:none;color:#0078b6;text-align: left;" href="`)
		hero.EscapeHTML(news.Link, buffer)
		buffer.WriteString(`">`)
		hero.EscapeHTML(news.Title, buffer)
		buffer.WriteString(`</a>
        </div>
        <div style="margin: 0px,20px; height: 0.5px; background-color:#f2f2f5;"></div>
    `)
	}
	buffer.WriteString(`
    <h3 style="margin-top: 20px;margin-bottom: 20px;background-color:#3385ff;color:white">Baidu热搜</h3>
    `)
	for index, news := range bList {
		indexs := strconv.Itoa(index + 1)
		buffer.WriteString(`
        <div style="display: flex;margin-top:5px;height: 30px;line-height: 30px;justify-content: space-around;align-items: center;">
            <p style="width:20%; color:red;">`)
		hero.EscapeHTML(indexs, buffer)
		buffer.WriteString(`</p>
            <a style="width:80%; text-decoration:none;color:#3385ff;text-align: left;" href="`)
		hero.EscapeHTML(news.Link, buffer)
		buffer.WriteString(`">`)
		hero.EscapeHTML(news.Title, buffer)
		buffer.WriteString(`</a>
        </div>
        <div style="margin: 0px,20px; height: 0.5px; background-color:#f2f2f5;"></div>
    `)
	}
	buffer.WriteString(`
    </div>
`)

	buffer.WriteString(`
    </body>
</html>`)

}
